export const FORM_VALIDATION = "FORM_VALIDATION";

export const SET_HEIGHT_OF_HEADER = "SET_HEIGHT_OF_HEADER";
export const HIDE_LEFT_CONTENT_OF_CREATIVE_AGENCY =
  "HIDE_LEFT_CONTENT_OF_CREATIVE_AGENCY";
export const SHOW_LEFT_CONTENT_OF_CREATIVE_AGENCY =
  "SHOW_LEFT_CONTENT_OF_CREATIVE_AGENCY";
export const HIDE_SHAPE_ON_MIDDLE_CONTENT_AND_RIGHT_CONTENT =
  "HIDE_SHAPE_ON_MIDDLE_CONTENT_AND_RIGHT_CONTENT";
export const SHOW_SHAPE_ON_MIDDLE_CONTENT_AND_RIGHT_CONTENT =
  "SHOW_SHAPE_ON_MIDDLE_CONTENT_AND_RIGHT_CONTENT";
export const GET_STYLE_FOR_THREE_CONTENT = "WIDTH_FOR_THREE_CONTENT";
export const GET_STYLE_FOR_TWO_CONTENT = "WIDTH_FOR_TWO_CONTENT";
export const ORANGE_SHAPE_STYLE_LEFT_CONTENT =
  "ORANGE_SHAPE_STYLE_LEFT_CONTENT";
export const PINK_SHAPE_STYLE_LEFT_CONTENT = "PINK_SHAPE_STYLE_LEFT_CONTENT";
export const MAUVE_SHAPE_STYLE_LEFT_CONTENT = "MAUVE_SHAPE_STYLE_LEFT_CONTENT";
export const PINK_SHAPE_STYLE_MIDDLE_CONTENT =
  "PINK_SHAPE_STYLE_MIDDLE_CONTENT";
export const SHOW_RIGHT_CONTENT = "SHOW_RIGHT_CONTENT";
export const HIDE_RIGHT_CONTENT = "HIDE_RIGHT_CONTENT";
export const ORANGE_SHAPE_STYLE_RIGHT_CONTENT =
  "ORANGE_SHAPE_STYLE_RIGHT_CONTENT";
export const BLUE_SHAPE_STYLE_RIGHT_CONTENT = "BLUE_SHAPE_STYLE_RIGHT_CONTENT";
export const HEPATIC_SHAPE_STYLE_RIGHT_CONTENT =
  "HEPATIC_SHAPE_STYLE_RIGHT_CONTENT";
export const PATHS_STYLE_RIGHT_CONTENT = "PATHS_STYLE_RIGHT_CONTENT";

export const CHANGE_COLORS_OF_LOGO = "CHANGE_COLORS_OF_LOGO";
export const CHANGE_NAVIGATION_STYLE = "CHANGE_NAVIGATION_STYLE";
export const DEFAULT_NAVIGATION_STYLE = "DEFAULT_NAVIGATION_STYLE";

export const SET_PROFILE_LENGTH_AND_TRANSLATE =
  "SET_PROFILE_LENGTH_AND_TRANSLATE";
export const RIGHT_ARROW_CONTROL = "RIGHT_ARROW_CONTROL";
export const LEFT_ARROW_CONTROL = "LEFT_ARROW_CONTROL";

export const SIDE_NAVIGATION_STYLE = "SIDE_NAVIGATION_STYLE";
